language: rust
rust:
  - nightly
  - stable
sudo: false

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo test --manifest-path duktape-sys/Cargo.toml
  - cargo test
  - cargo doc

deploy:
  - provider: script
    script:
      - cd target/doc
      - git init
      - git config user.email 'nobody@nobody.org'
      - git config user.name 'Travis CI'
      - git add .
      - git commit -m "Generate rustdoc for $TRAVIS_COMMIT"
      - git push --force "https://${GITHUB_TOKEN}@github.com/dflemstr/duk.git" master:gh-pages
    skip_cleanup: true
    on:
      repo: dflemstr/rq

