language: rust
rust:
  - nightly
  - stable
env:
sudo: false

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    - FEATURES="--no-default-features"
    - FEATURES="--features debug" FEATURE_DOC=true
    - FEATURES="--features trace"
    - FEATURES="--features spam"

script:
  - cargo test $FEATURES
  - cargo doc

deploy:
  - provider: script
    script: ./deploy-doc
    skip_cleanup: true
    on:
      repo: dflemstr/duk
      rust: stable
      condition: $FEATURE_DOC = true
