language: rust
rust:
  - nightly
  - stable
sudo: false

env:
  global:
    - RUST_BACKTRACE=1

script:
  - cargo test
  - cargo doc --no-deps

deploy:
  - provider: script
    script: ./deploy-doc
    skip_cleanup: true
    on:
      repo: dflemstr/duk
      rust: stable
