#!/bin/sh -eu

cd target/doc
git init
git config user.email 'nobody@nobody.org'
git config user.name 'Travis CI'
git add .
git commit -qm "Generate rustdoc for $TRAVIS_COMMIT"
git push --force "https://${GITHUB_TOKEN}@github.com/dflemstr/duk.git" master:gh-pages
