(function() {var implementors = {};
implementors["libc"] = [];implementors["duktape_sys"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duktape_sys/struct.duk_memory_functions.html' title='duktape_sys::duk_memory_functions'>duk_memory_functions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duktape_sys/struct.duk_function_list_entry.html' title='duktape_sys::duk_function_list_entry'>duk_function_list_entry</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duktape_sys/struct.duk_number_list_entry.html' title='duktape_sys::duk_number_list_entry'>duk_number_list_entry</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duktape_sys/struct.duk_time_components.html' title='duktape_sys::duk_time_components'>duk_time_components</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duktape_sys/struct.duk_double_union.html' title='duktape_sys::duk_double_union'>duk_double_union</a>",];implementors["backtrace"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='backtrace/struct.Backtrace.html' title='backtrace::Backtrace'>Backtrace</a>",];implementors["error_chain"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='error_chain/struct.Backtrace.html' title='error_chain::Backtrace'>Backtrace</a>",];implementors["duk"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='duk/struct.ContextBuilder.html' title='duk::ContextBuilder'>ContextBuilder</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
